# Generated by Django 5.2.4 on 2025-08-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('code', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('operator', models.SmallIntegerField(choices=[(1, 'DR'), (-1, 'CR')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4'), (5, 'Special Periods')], db_index=True, default=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, unique=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=186, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYearPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=False)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fiscalyear')),
                ('default_budget', models.ForeignKey(blank=True, limit_choices_to={'code__in': [3, 4]}, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('code', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('posting', models.BooleanField(default=False)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accounttype')),
                ('active_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_active_from', to='core.fiscalyearperiod')),
                ('active_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_active_to', to='core.fiscalyearperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(db_index=True, max_length=7, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisation_active_from', to='core.fiscalyearperiod')),
                ('active_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_active_to', to='core.fiscalyearperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[(1, 'Period 01'), (2, 'Period 02'), (3, 'Period 03'), (4, 'Period 04'), (5, 'Period 05'), (6, 'Period 06'), (7, 'Period 07'), (8, 'Period 08'), (9, 'Period 09'), (10, 'Period 10'), (11, 'Period 11'), (12, 'Period 12'), (13, 'Period 13'), (14, 'Period 14'), (15, 'Period 15'), (16, 'Period 16')], db_index=True, unique=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fiscalquarter')),
            ],
        ),
        migrations.AddField(
            model_name='fiscalyearperiod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.period'),
        ),
        migrations.CreateModel(
            name='PeriodMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.period')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('code', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=186, unique=True)),
                ('active_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_active_from', to='core.fiscalyearperiod')),
                ('active_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_active_to', to='core.fiscalyearperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('working_forecast', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('original_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revised_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('fiscal_year_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fiscalyearperiod')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project')),
            ],
            options={
                'verbose_name_plural': 'Financial Data',
            },
        ),
        migrations.AddConstraint(
            model_name='fiscalyearperiod',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'period'), name='unique_fiscal_year_period'),
        ),
        migrations.AddConstraint(
            model_name='periodmonth',
            constraint=models.UniqueConstraint(fields=('period', 'month'), name='unique_period_month'),
        ),
        migrations.AddConstraint(
            model_name='financialdata',
            constraint=models.UniqueConstraint(fields=('fiscal_year_period', 'organisation', 'account', 'project'), name='unique_fiscal_year_period_organisation_account_project'),
        ),
    ]
